### PR TITLE
Add first decorator

### LINKED ISSUE #120: Decorators!
e.g.:

```
@pycallgraph.decorators.trace(output=GraphvizOutput())
def method():
    pass
```

### PR DESCRIPTION
**Pull request by luzfcb**
fix #120 
port from https://github.com/ivannotes/pycallgraph/commit/0b2fb090a6dd2664235600af149f390cdabc3b00 by @ivannotes

TODO: docs

### CODE REVIEW

**Comment by gak** [comment]
Thanks for this @luzfcb 

I realise you originally copied @ivanotes diff, but I would like a few things before I accept this pull request:
* Rename the decorator function to `trace` in a new `decorators` module, similar to the example in #120 
* Remove the default `output` argument, so it acts the same way as `PyCallGraph()`.
* Move the new tests into a test_decorators.py, and have similar tests to test_pycallgraph.py where it checks for no arguments, as well as a normally working test.

**Comment by luzfcb** [comment]
@gak Done.

**Comment by gak** [comment]
Excellent, thanks. Also thanks for making it a wheel build too!

@ChangeTip, send a beer to @luzfcb

**Comment by changetip** [comment]
Hi @luzfcb, @gak sent you a Bitcoin tip worth a beer (15,169 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/849940)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by luzfcb** [comment]
@gak it is still necessary to add any documentation for this and see if the decorator tests really test the decorator correctly /o\ ...

**Comment by gak** [comment]
Up to you of course. When I eventually get around to making a new release, I'm happy to do the testing and docs myself.

**Pull request merged**
